name: Build
run-name: Building go WASM
on: [push]
jobs:
  build:
    name: Compile Wasm
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go environment
      uses: actions/setup-go@v5.0.2
    - name: compile go
      run: GOOS=js GOARCH=wasm go build -o app.wasm .
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.2.1-node20
      with:
        name: artifact
        path: app.wasm index.html style.css script.js wasm_exec.js
  
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
